account/urls.py
from django.contrib.auth.views import LogoutView,LoginView
from django.urls import path
from .views import signup

urlpatterns = [
    path('signup/',signup,name='signup'),
    path('login/',LoginView.as_view(template_name='account/login.html'),name='login'), 
    path('logout/',LogoutView.as_view(),name='logout')
]

chango/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('core.urls')),
    path('', include('account.urls')),
    path('spaces/',include('space.urls')),
    path('admin/', admin.site.urls),
]

core/urls.py
from django.urls import path

from . import views

app_name = 'core'


urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
]

space/urls.py
from django.urls import path
from .views import spaces, space

urlpatterns = [
    path('',spaces,name='spaces'),
    path('<slug:slug>/',space, name='space')
]

space/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify

class Space(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True,blank=True)
    description = models.CharField(max_length=1000, blank=True)
    created_by = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

    def save(self, *args, **kwargs):
        if not self.description:
            self.description = f"{self.created_by.username}'s Space"
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name
    
class Message(models.Model):
    space = models.ForeignKey(Space,related_name='messages',on_delete=models.CASCADE)
    user = models.ForeignKey(User,related_name='messages',on_delete=models.CASCADE)
    content = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('date_added',)

account/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class SignUpForm(UserCreationForm):
    class meta:
        model = User
        fields = ['username','password1','password2']

account/views.py
from django.contrib.auth import login
from django.shortcuts import render, redirect
from .forms import SignUpForm

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)

        if form.is_valid():
            user = form.save()
            login(request,user)

            return redirect('/')
    else:
        form = SignUpForm()

    return render(request,'account/signup.html',{'form':form})

core/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'core/index.html')


def about(request):
    return render(request, 'core/about.html')

space/views.py
from django.shortcuts import render
from .models import Space, Message
from django.contrib.auth.decorators import login_required

@login_required
def spaces(request):
    spaces = Space.objects.all()
    return render(request,'space/spaces.html',{'spaces':spaces})

@login_required
def space(request, slug):
    space = Space.objects.get(slug=slug)
    messages = Message.objects.filter(space=space)[:30]
    return render(request, 'space/space_detail.html',{'space':space,'messages':messages})

core/templates/core/about.html
{% extends 'core/base.html' %}

{% block title %}About Us | {% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col s12 m10 offset-m1 lg:p-20">
            <h1 class="flow-text text-center">About Django Channels</h1>
            <p class="flow-text text-justify teal-text">
                Django Channels is a project that extends the capabilities of Django beyond HTTP to handle WebSockets, chat protocols, IoT protocols, and more.
                It's built on a Python specification called ASGI (Asynchronous Server Gateway Interface) and provides the choice to handle other connections in either a synchronous or asynchronous style.
            </p>
            <br/>
            <p class="flow-text text-justify amber-text">
                Unlike the core Django framework, Channels isn’t underpinned by WSGI; instead, it’s built on a newer Python spec called ASGI which supports both synchronous and asynchronous code.
                Channels extends Django’s capabilities, making it possible to handle not only HTTP but also WebSockets, MQTT (IoT), chatbots, radios, and other real-time applications.
            </p>
            <br/>
            <p class="flow-text text-justify green-text">
                Django Channels offers a certain degree of flexibility, allowing you to configure your new Django project in a way that makes the most sense for your use case.
                It has multi-protocol support, enabling the use of WebSockets, HTTP (including HTTP/2, long-polling, and Server-Sent Events), and other options like chat and IoT protocols.
            </p>
            <br/>
            <p class="flow-text text-justify deep-orange-text">
                Channels supports a 1:1 messaging pattern, but it also allows you to broadcast events to multiple consumers via channels. Channels provides different routing classes which allow you to combine and stack consumers, similar to Django's URLs.
            </p>
            <br/>
            <p class="flow-text text-justify blue-text">
                Channels is comprised of several packages: channels, the Django integration layer; daphne, the HTTP and Websocket termination server; asgiref, the base ASGI library; and channels_redis, the Redis channel layer backend (optional).
                Channels builds upon the native ASGI support in Django, giving you the choice to handle other connections in either a synchronous or asynchronous style.
            </p>
            <br/>
            <p class="flow-text text-justify purple-text">
                Channels is a powerful tool for building real-time applications and can be used to power a wide range of use cases, from chat applications to IoT protocols.
            </p>
        </div>
    </div>
</div>
{% endblock %}

core/templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}Chango</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.min.css' %}">
    <style>
        body {
            font-family: 'Roboto', sans-serif;
            background-color: #f5f5f5;
        }

        nav {
            background-color: #26a69a;
            border-radius: 0 0 10px 10px;
        }

        nav a {
            color: #fff;
            font-weight: bold;
        }

        nav a:hover {
            text-decoration: underline;
        }

        .container-content {
            padding: 20px;
        }

        .btn-teal {
            background-color: #26a69a;
        }

        .btn-teal:hover {
            background-color: #009688;
        }

        .welcome-message {
            background-color: #fff;
            border-radius: 5px;
            padding: 15px;
            margin-bottom: 20px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }
    
        .welcome-message p {
            color: #333;
            font-size: 18px;
        }

        .chat-messages {
            height:400px;
            overflow-y:auto;
        }
    </style>
</head>

<body>

    <nav class="container mx-auto">
        <div class="nav-wrapper">
            <a href="{% url 'core:index' %}" class="brand-logo left">Chango</a>
            <ul id="nav-desktop" class="right">
                {% if request.user.is_authenticated %}
                    <li><a href="/spaces/">Spaces</a></li>
                    <li><a href="/logout/" class="btn btn-teal">Log out</a></li>
                {% else %}
                    <li><a href="{% url 'core:about' %}">About</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="container container-content">
        {% block content %}
        {% endblock %}
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var elems = document.querySelectorAll('.sidenav');
            var instances = M.Sidenav.init(elems, {});
        });
    </script>
    {% block scripts %}
    {% endblock %}
</body>

</html>

core/templates/core/index.html
{% extends 'core/base.html' %}

{% load static %}

{% block content %}
{% if request.user.is_authenticated %}
        <div class="container container-content welcome-message">
            <p>Welcome, {{request.user.username }}! Go to Spaces section to explore</p>
        </div>
{% endif %}
    <div class="container mt-5">
        <div class="row">
            <div class="col s12 m12 l10 offset-l1">
                {% if not request.user.is_authenticated %}
                    <div class="card-panel teal lighten-2 center-align">
                        <p class="flow-text text-gray-800 mb-4">
                            Login/Sign up to create your space and start chatting!
                        </p>
                        <a href="/login/" class="waves-effect waves-light btn teal darken-3">Login</a>
                        <a href="/signup/" class="waves-effect waves-light btn teal darken-3">Sign Up</a>
                    </div>
                {% endif %}
                <div class="card-panel teal lighten-4">
                    <div class="row">
                        <div class="col s12 m4 mb-4">
                            <div class="center-align">
                                <h3 class="flow-text text-gray-800">Real-Time Updates</h3>
                                <p class="mb-0 text-gray-600">Django-channels empower Chango to provide real-time updates, enhancing user experience.</p>
                            </div>
                        </div>

                        <div class="col s12 m4 mb-4">
                            <div class="center-align">
                                <h3 class="flow-text text-gray-800">Scalable Architecture</h3>
                                <p class="mb-0 text-gray-600">Chango's architecture ensures scalability and reliability as your user base grows.</p>
                            </div>
                        </div>

                        <div class="col s12 m4 mb-4">
                            <div class="center-align">
                                <h3 class="flow-text text-gray-800">Secure Communication</h3>
                                <p class="mb-0 text-gray-600">Chango prioritizes security, ensuring safe and encrypted communication.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

space/templates/space/space_detail.html
{% extends 'core/base.html' %}

{% block title %}{{ space.name }} | {% endblock %}

{% block content %}
<div class="container mx-auto">
    <div class="card white lighten-2 rounded">
        <div class="card-content">
            <div class="chat-messages" id="chat-messages">
                {% for message in messages %}
                    <b> {{message.user.username}}:</b>{{message.content}}<br>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

<div class="container mt-6">
    <form method="post" action="." class="row">
        <div class="input-field col s8">
            <input type="text" name="content" placeholder="Your message..." id="chat-message-input">
            <label for="chat-message-input">Your message...</label>
        </div>

        <div class="col s4">
            <button class="btn waves-effect waves-light teal" type="submit" id="chat-message-submit">Submit</button>
        </div>
    </form>
</div>

{% endblock %}

{% block scripts %}
{{ space.slug|json_script:"json-spacename" }}
{{ request.user.username|json_script:"json-username" }}

<script>
    const spaceName = JSON.parse(document.getElementById('json-spacename').textContent);
    const userName = JSON.parse(document.getElementById('json-username').textContent);
    
    const chatSocket = new WebSocket(
        'ws://' + window.location.host + '/ws/' + spaceName + '/'
    )
    chatSocket.onmessage = function(e) {
        console.log('sendmsg')
        const data = JSON.parse(e.data);
        if(data.message) {
            document.querySelector('#chat-messages').innerHTML += ('<b>' + data.username + '</b>: ' + data.message + '<br>');
            } else {
            alert('empty message!')
        }
    }
    chatSocket.onclose = function(e) {
        console.log('closed')
    }

    document.querySelector('#chat-message-submit').onclick = function(e) {
        e.preventDefault();
        const msgInptDom = document.querySelector('#chat-message-input');
        const msg = msgInptDom.value;
        chatSocket.send(JSON.stringify({
            'message':msg,
            'username':userName,
            'space':spaceName
        }));
        msgInptDom.value = '';
        return false
    };

</script>
{% endblock %}

space/templates/space/spaces.html
{% extends 'core/base.html' %}

{% block title %}Spaces | {% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row center-align">
        <div class="col s12">
            <h1 class="black-text text-darken-4 flow-text">Spaces</h1>
        </div>
    </div>

    <div class="row">
        {% for space in spaces %}
            <div class="col s12 m6 l3">
                <div class="card grey lighten-3"> <!-- Light gray background -->
                    <div class="card-content">
                        <span class="red-text text-darken-4">{{ space.name }}</span> <!-- Teal text color -->
                        <p class="teal-text text-darken-2">{{ space.description }}</p>
                    </div>
                    <div class="card-action">
                        <a href="{% url 'space' space.slug %}" class="blue-text text-darken-4">Join</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}